name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push frontend_react image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend_react
          file: ./frontend_react/Dockerfile
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/mrcord/howtofinddrugsonline
          tags: ghcr.io/mrcord/howtofinddrugsonline/frontend_react:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/mrcord/howtofinddrugsonline
          tags: ghcr.io/mrcord/howtofinddrugsonline/backend:latest